### ISSUE TITLE
[ERROR] - Post "/cm/api/v1/cluster-management/get-cluster-ids": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by akshatagarwl** [accuknox/discovery-engine#332]
```
humancalico@nixos ~/r/k/src (dev) [SIGINT]> make && bash ../scripts/start_service.sh
# for build_image -> CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-s -w' -o knoxAutoPolicy main.go
#cd /home/humancalico/repos/knoxAutoPolicy/src; go mod tidy; go build -tags debugger -gcflags="all=-N -l" -o knoxAutoPolicy main.go
cd /home/humancalico/repos/knoxAutoPolicy/src; go mod tidy; go build -o knoxAutoPolicy main.go
4:10PM INF logging/logger.go:48 > logging configured fileLogging=false fileName=service.log jsonLogOutput=false logDirectory=log maxAgeInDays=5 max
Backups=5 maxSizeMB=10
4:10PM INF feedconsumer/consumer.go:337 > 3 Knox feed consumer(s) started
4:10PM INF feedconsumer/consumer.go:354 > Knox feed consumer(s) started
4:10PM INF networkpolicy/networkPolicy.go:1627 > Auto network policy discovery cron job started
4:10PM ERR systempolicy/systemPolicy.go:257 > System log from not correct:
4:10PM INF systempolicy/systemPolicy.go:716 > Auto system policy discovery onetime job done
4:10PM INF main.go:50 > KnoxAutoPolicy gRPC server on 9089 port started
4:10PM INF feedconsumer/consumer.go:332 > There is already running consumer(s)
4:10PM INF feedconsumer/consumer.go:132 > Starting consumer 3, topics: [cilium-telemetry-new cilium-alerts]
4:10PM INF feedconsumer/consumer.go:132 > Starting consumer 2, topics: [cilium-telemetry-new cilium-alerts]
4:10PM INF feedconsumer/consumer.go:132 > Starting consumer 1, topics: [cilium-telemetry-new cilium-alerts]
4:10PM INF networkpolicy/helperFunctions.go:240 > Get network log from the kafka consumer
4:10PM INF plugin/cilium.go:792 > The total number of cilium kafka traffic flow: [37700]
4:10PM INF networkpolicy/networkPolicy.go:1543 > Network policy discovery started for cluster [localhost]
4:10PM ERR cluster/clusterMgmtHandler.go:65 > Error on response.
[ERROR] - Post "/cm/api/v1/cluster-management/get-cluster-ids": unsupported protocol scheme ""
4:10PM ERR networkpolicy/networkPolicy.go:1551 > Cluster localhost not onboarded
4:10PM INF networkpolicy/helperFunctions.go:240 > Get network log from the kafka consumer
```

cluster: minikube

```
humancalico@nixos ~> minikube ssh
docker@minikube:~$ uname -a
Linux minikube 5.14.1 #1-NixOS SMP Fri Sep 3 08:24:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

feeder service config:
```
KAFKA_URL=127.0.0.1
KAFKA_PORT=9092
HUBBLE_URL=localhost
HUBBLE_PORT=4245
HUBBLE_ENABLED=true
KUBEARMOR_ENABLED=false
KAFKA_SSL_ENABLED=false
KAFKA_PORT=9092
KAFKA_ENABLED=true
KAFKA_TOPIC_FOR_CILIUM_TELEMETRY=cilium-telemetry-new
KAFKA_TOPIC_FOR_CILIUM_ALERT=cilium-alerts
```

knoxAutoPolicy config:
```yaml
application:
  name: knoxautopolicy
  network:
    operation-mode: 1                         # 1: cronjob | 2: one-time-job
    operation-trigger: 1000
    cron-job-time-interval: "0h0m10s"         # format: XhYmZs 
    network-log-limit: 100000
    network-log-from: "kafka"                # db|hubble|kafka
    network-log-file: "./flow.json"           # file path
    network-policy-to: "db|file"              # db, file
    network-policy-dir: "./"

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: password
  dbname: accuknox
  table-network-log: network_log
  table-network-policy: network_policy
  table-system-log: system_log
  table-system-alert: system_alert
  table-system-policy: system_policy

feed-consumer:
  kafka:
    number-of-consumers: 3
    broker-address-family: v4
    session-timeout-ms: 6000
    auto-offset-reset: "earliest"
    # auto-offset-reset: "latest"
    bootstrap-servers: "localhost:9092"
    group-id: knoxautopolicy
    topics: 
      - cilium-telemetry-new
      - cilium-alerts
    security:
      protocol: SSL
    ssl:
      enabled: false
    ca:
      location: /kafka-ssl/ca.pem
    keystore:
      location: /kafka-ssl/user.p12
      pword: DHmHwNYy22At
    events:
      buffer: 50

logging:
  level: "INFO"

# kubectl -n kube-system port-forward service/hubble-relay --address 0.0.0.0 --address :: 4245:80
cilium-hubble:
  url: localhost
  port: 4245

kubearmor:
  url: localhost
  port: 32767

```
