### ISSUE TITLE
Generated cilium policy -- Formatting issue

### ISSUE THREAD

**Issue by seswarrajan** [accuknox/discovery-engine#468]
### Environment
1. k8s cluster (minikube)
2. cilium + hubble running
3. discovery-engine running

### Steps
1. In the described cluster, deploy GKE microservices demo deployment. 
2. On doing so let discovery-engine generate cilium policies.
3. Get generated policies using accuknox cli ==> accuknox discover -p cilium -f yaml > policy.yaml
4. Now apply this yaml

### **Generated cilium policy**
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: autopol-egress-emfxcjytdkeojfm
  namespace: explorer
spec:
  egress:
  - toEntities:
    - host,kube-apiserver
    toPorts:
    - ports:
      - port: "8443"
        protocol: TCP
  endpointSelector:
    matchLabels:
      container: knoxautopolicy
```

The above generated policy has the values for toEntities separated by a comma(,). This is not valid. There should be a new entry for the same. The final policy should look like.

### **Expected cilium policy**
```
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: autopol-egress-emfxcjytdkeojfm
  namespace: explorer
spec:
  egress:
  - toEntities:
    - host
    - kube-apiserver
    toPorts:
    - ports:
      - port: "8443"
        protocol: TCP
  endpointSelector:
    matchLabels:
      container: knoxautopolicy
```
