### ISSUE TITLE
Hardening policies only getting generated for deployments

### ISSUE THREAD

**Issue by vishnusomank** [accuknox/discovery-engine#670]
### Problem Statement:
The discovery engine is not able to recommend hardening policies if the pods are generated through a statefulset or a replicaset. With the current implementation the discovery engine checks for all deployments in the Kubernetes cluster and generates the recommended/hardening policies. 

### Steps to reproduce the issue:

1. Create a [k3s cluster](https://github.com/kubearmor/KubeArmor/tree/main/contribution/k3s)
2. Install karmor cli 
    ```
    curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin
    ```
3. Install kubearmor
    ```
    karmor install
    ```
4. Deploy `frontend` pod using replicaset
    ```
    kubectl create ns rs-demo
    echo "
    apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      name: frontend
      labels:
        app: guestbook
        tier: frontend
    spec:
      # modify replicas according to your case
      replicas: 3
      selector:
        matchLabels:
          tier: frontend
      template:
        metadata:
          labels:
            tier: frontend
        spec:
          containers:
          - name: php-redis
            image: gcr.io/google_samples/gb-frontend:v3 " | kubectl -n rs-demo apply -f- 
    ```
5. use karmor recommend to generate hardening policy
    ```
    karmor recommend -n rs-demo
    ```

The default output folder `out` will be empty, meaning no policies generated for the pods
