### ISSUE TITLE
fix: discovered K8s network policies

### ISSUE THREAD

**Issue by Ankurk99** [accuknox/discovery-engine#688]
**Description**
The currently discovered network policies are not working as expected with CNI.

**Environment**
CNI - Calico
K8s - k3s

**Observed behaviour**
One of the discovered k8s network ingress policy:
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: autopol-ingress-fghnkajtjgsitll
  namespace: demo-app
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: loadgenerator
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
```
But the above policy when applied is not working as expected.

**Expected policy**
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: autopol-ingress-fghnkajtjgsitll
  namespace: demo-app
spec:
  ingress:
  # - ports:
  #   - port: 8080
  #     protocol: TCP
  - from:
    - podSelector:
        matchLabels:
          app: loadgenerator
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
```
Removing the global ports ingress condition makes the policy to work as expected. 
What is the role of adding this particular rule?
