### ISSUE TITLE
enhancement (hardening policies): merging the hardening policies

### ISSUE THREAD

**Issue by yasin-cs-ko-ak** [accuknox/discovery-engine#692]
## Description:
As of right now we are getting many recommend hardening policies for workloads and it's difficult for them go and analyse each policy and apply them. To simplify that we are merging the policies per deployment/labels to show in the AccuKnox SaaS. So it'll simplify the policy.

This is how the merged policy structure will look like:
```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata: 
  name: ksp-hardening-policies
  namespace: default
spec:
  selector: 
    matchLabels: 
      app: app
  file:
    matchPaths:
    - path:
      readOnly:
      action:
      severity:
      message:
      tags:
    matchDirectories:
    - dir: 
      recursive: 
      readOnly: 
      action: 
      severity: 
      message: 
      tags: 
  process:
    matchPaths:
    - path:
      readOnly:
      action:
      severity:
      message:
      tags:
    matchDirectories:
    - dir:
      recursive:
      readOnly:
      action:
      severity:
      message:
      tags:
```
