### ISSUE TITLE
Refine RBAC permissions for discovery-engine clusterrole

### ISSUE THREAD

**Issue by rksharma95** [accuknox/discovery-engine#753]
```yaml
- apiGroups: ["*"]
  resources: ["pods", "services", "deployments", "endpoints", "namespaces", "nodes","replicasets", "statefulsets", "daemonsets", "secrets"]
  verbs: ["get", "list", "watch","create", "update", "delete"]
```

analyze and use only required permissions for each resource in the discovery-engine clusterrole rbac rules.
i.e. create, update and delete permissions for node is not required imo.
