### ISSUE TITLE
CI latest release workflow testing stable image instead of latest changes

### ISSUE THREAD

**Issue by rksharma95** [accuknox/discovery-engine#756]
in the [latest-release](https://github.com/accuknox/discovery-engine/blob/dev/.github/workflows/latest-release.yml) CI workflow, it's running the stable image of the discovery-engine instead of the built image with latest changes.

```yaml
- name: Run discovery engine
        run: |
            kubectl apply -f deployments/k8s/ && kubectl wait --for=condition=ready --timeout=5m -n accuknox-agents pod -l app=discovery-engine            
            kubectl get pods -A
```

Use the same image built in the CI workflow itself to test the latest changes.
